"""``papers`` table CRUD (Week 1 ingestion pipeline)."""

import uuid
from datetime import date
from typing import Any

from sqlalchemy import text

from app.memory.db.engine import get_engine


async def insert_paper(
    *,
    paper_id: uuid.UUID,
    user_id: uuid.UUID,
    s3_key: str,
    title: str | None = None,
    authors: list[str] | None = None,
    arxiv_id: str | None = None,
    doi: str | None = None,
    published_at: date | None = None,
) -> None:
    """Insert a new ``papers`` row with ``status='pending'``.

    ``paper_id``/``s3_key`` are generated by the caller (route handler)
    *before* this call so the S3 upload key (``papers/<paper_id>.pdf``)
    can be written in the same row, rather than needing a follow-up update.
    """
    engine = get_engine()
    async with engine.engine.begin() as conn:
        await conn.execute(
            text(
                """
                INSERT INTO papers
                    (id, user_id, title, authors, arxiv_id, doi, published_at, s3_key, status)
                VALUES
                    (:id, :user_id, :title, :authors, :arxiv_id, :doi, :published_at, :s3_key,
                     'pending')
                """
            ),
            {
                "id": str(paper_id),
                "user_id": str(user_id),
                "title": title,
                "authors": authors,
                "arxiv_id": arxiv_id,
                "doi": doi,
                "published_at": published_at,
                "s3_key": s3_key,
            },
        )


async def update_paper_status(
    paper_id: uuid.UUID | str, status: str, *, fail_reason: str | None = None
) -> None:
    """Update a paper's ``status`` (and, on failure, its ``fail_reason``)."""
    engine = get_engine()
    async with engine.engine.begin() as conn:
        await conn.execute(
            text("UPDATE papers SET status = :status, fail_reason = :fail_reason WHERE id = :id"),
            {"status": status, "fail_reason": fail_reason, "id": str(paper_id)},
        )


async def list_papers(user_id: uuid.UUID | str) -> list[dict[str, Any]]:
    """List all papers for ``user_id``, newest first, with chunk counts."""
    engine = get_engine()
    async with engine.engine.connect() as conn:
        result = await conn.execute(
            text(
                """
                SELECT p.id, p.title, p.authors, p.arxiv_id, p.status, p.fail_reason,
                       p.ingested_at,
                       (SELECT count(*) FROM chunks c WHERE c.paper_id = p.id) AS chunk_count
                FROM papers p
                WHERE p.user_id = :user_id
                ORDER BY p.ingested_at DESC
                """
            ),
            {"user_id": str(user_id)},
        )
        rows = result.mappings().all()
    return [
        {
            "id": str(row["id"]),
            "title": row["title"],
            "authors": list(row["authors"]) if row["authors"] is not None else None,
            "arxiv_id": row["arxiv_id"],
            "status": row["status"],
            "fail_reason": row["fail_reason"],
            "ingested_at": row["ingested_at"],
            "chunk_count": int(row["chunk_count"]),
        }
        for row in rows
    ]


async def get_paper_status(paper_id: uuid.UUID | str) -> dict[str, Any] | None:
    """Fetch a single paper's status/fail_reason/chunk_count, or ``None``."""
    engine = get_engine()
    async with engine.engine.connect() as conn:
        result = await conn.execute(
            text(
                """
                SELECT p.id, p.status, p.fail_reason,
                       (SELECT count(*) FROM chunks c WHERE c.paper_id = p.id) AS chunk_count
                FROM papers p WHERE p.id = :id
                """
            ),
            {"id": str(paper_id)},
        )
        row = result.mappings().first()
    if row is None:
        return None
    return {
        "id": str(row["id"]),
        "status": row["status"],
        "fail_reason": row["fail_reason"],
        "chunk_count": int(row["chunk_count"]),
    }


async def delete_paper(paper_id: uuid.UUID | str) -> None:
    """Delete a paper and everything that FK-references it, in one transaction.

    Order matters -- foreign keys chain paper -> claims -> contradictions and
    paper -> chunks, with claims also referencing chunks (``source_chunk_id``),
    so a naive "delete chunks then paper" fails on the ``claims.paper_id`` /
    ``claims.source_chunk_id`` references. We tear down dependents first:
    contradictions citing this paper's claims, then the claims, then chunks,
    then the paper row itself. Entities are user-scoped (shared across papers),
    so they are deliberately left in place. The S3 object is not touched.
    """
    engine = get_engine()
    async with engine.engine.begin() as conn:
        await conn.execute(
            text(
                """
                DELETE FROM contradictions
                WHERE claim_a_id IN (SELECT id FROM claims WHERE paper_id = :id)
                   OR claim_b_id IN (SELECT id FROM claims WHERE paper_id = :id)
                """
            ),
            {"id": str(paper_id)},
        )
        await conn.execute(text("DELETE FROM claims WHERE paper_id = :id"), {"id": str(paper_id)})
        await conn.execute(text("DELETE FROM chunks WHERE paper_id = :id"), {"id": str(paper_id)})
        await conn.execute(text("DELETE FROM papers WHERE id = :id"), {"id": str(paper_id)})
